services:
  - type: web
    name: barter-backend
    env: docker
    plan: free
    repo: https://github.com/VviratT/BarterSkills
    branch: main
    dockerfilePath: BarterSkillsBackend/Dockerfile
    envVars:
      - key: PORT
        value: "8000"
      - key: MONGODB_URI
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_PLAN_MONTHLY
        sync: false
      - key: RAZORPAY_PLAN_YEARLY
        sync: false
      - key: QG_URL
        sync: false
      - key: HF_API_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        sync: false

  - type: web
    name: barter-python
    env: docker
    plan: free
    repo: https://github.com/VviratT/BarterSkills
    branch: main
    dockerfilePath: BarterSkillsBackend/Dockerfile.python
    envVars:
      - key: PORT
        value: "10000"
      - key: HF_API_KEY
        sync: false
      - key: WHISPER_CMD
        sync: false
